# docker-compose.yml - Only for local debug purposes
services:
  mysql:
    image: mysql:8
    container_name: local-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test_db
    volumes:
      - ./.mysql-data:/var/lib/mysql
